language: cpp
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-8
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - g++-9
      - clang-8
      - libboost-all-dev
      - libssl-dev
      - cmake
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

script: cmake CMakeLists.txt && make && ./tests/bin/tests
